export const REGISTRO_CORRECTO = 'REGISTRO_CORRECTO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUSARIO';
export const LOGIN_CORRECTO = 'LOGIN_CORRECTO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
